### ISSUE TITLE
"@" character does not have intended result

### ISSUE THREAD

**Issue by tannerbaum** [peerigon/scrapegoat#25]
If you add a Twitter user in the description of a calendar event, Scrapegoat still treats it as a hashtag. We have on our home page right now an example of this which goes to a "No Results" page. 

![screen shot 2018-04-04 at 10 21 41](https://user-images.githubusercontent.com/1280597/38296602-1b93a574-37f2-11e8-80de-e1e535021310.png)

![screen shot 2018-04-04 at 10 22 54](https://user-images.githubusercontent.com/1280597/38296625-2aee06cc-37f2-11e8-9759-47e466df630a.png)

**Comment by leomelzer** [comment]
I believe the issue is in how we use the module here: https://github.com/peerigon/www/blob/dev/app/shared/components/MeetPeerigonEvents.js#L120

Scrapegoat is merely passing through the data as it is in the event. 

We basically snip the first character from the split list of tags (or whatever) and then prefix it with `#` (or `%23` encoded) for the Twitter search link. 

We should try to not overload the meaning of the event `description` as provided by scrapegoat for which we currently implement our own string-parsing in `www`.

Using additional fields however could require some implementation work in scrapegoat to support more event fields, see https://github.com/peerigon/scrapegoat/blob/master/lib/xml/parser.js#L224-L234.
